export const BLOCK_REPOSITORY = 'BLOCK_REPOSITORY';
export const BLOCK_SERVICE = 'BLOCK_SERVICE';

export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const TRANSACTION_SERVICE = 'TRANSACTION_SERVICE';

export const SEARCH_SERVICE = 'SEARCH_SERVICE';

export const PROPOSER_REPOSITORY = 'PROPOSER_REPOSITORY';
export const PROPOSER_SERVICE = 'PROPOSER_SERVICE';

export const CHALLENGED_BLOCK_REPOSITORY = 'CHALLENGED_BLOCK_REPOSITORY';

export const BLOCK_CREATION_SERVICE = 'BLOCK_CREATION_SERVICE';

export const CONTRACT_CLIENT_SERVICE = 'CONTRACT_CLIENT_SERVICE';
